### ISSUE TITLE
Modele + data manager

### ISSUE THREAD

**Issue by Lagger96** [Lagger96/wifi-notes#2]
Należy utworzyć modele: Network, NetworkCategory.
NetworkCategory powinno zawierać listę Network.

Dodatkowo należy utworzyć klasę DataManager (singleton) posiadającą metody:
getNetworks, getNetworkCategories, getNetwork, getNetworkCategory, addNetwork, updateNetwork, deleteNetwork.

Na tym etapie, każda z metod get* powinna zwracać zmockowane dane.
Podpięcie DAO w innym zadaniu.

**Comment by ilinoyer** [comment]
Dodane zgodnie z zaleceniami z tym, ze według mnie sam DataManager nie powinien być Singletonem. 
Singletonem powinien być DBHelper. 
@Touhou-fan proszę o CR
